name: auto_crop
description: >-
  Flutter package that allows auto cropping images 
  with a custom and adjustable shape. 
version: 1.0.1
homepage: https://github.com/eterkit/flutter-packages/tree/main/auto_crop
repository: https://github.com/eterkit/flutter-packages

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.5.0"


dependencies:
  flutter:
    sdk: flutter
  custom_cropper: ^1.0.3
  edge_detector: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

import_sorter:
  comments: false
