name: responsive_config
version: 0.1.9
description: >-
  Code generation package, that allows generating 
  responsive classes and responsive variables with annotations.
homepage: https://github.com/eterkit/flutter-packages/tree/main/responsive_config
repository: https://github.com/eterkit/flutter-packages

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  responsive_annotation: '>=0.1.6 <1.0.0'
  source_gen: ^1.2.2
  analyzer: ^4.2.0
  build: ^2.3.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0

flutter:

import_sorter:
  comments: false
