name: example
description: Example project for auto_animated_list package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_animated_list:
    # When depending on this package from a real application you should use:
    #   app_usage: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    path: ../
  fuzzy: 0.4.0-nullsafety.0

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true