name: permission_guard
description: >-
  UI wrapper around permission_handler package 
  that makes handling permission states easy.
version: 2.0.1
homepage: https://github.com/eterkit/flutter-packages/tree/main/permission_guard
screenshots:
  - description: 'Example of permission guard in a widget.'
    path: widget.gif
  - description: 'Example of permission guard in a dialog.'
    path: dialog.gif

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0

flutter:

import_sorter:
  comments: false
