name: calendly
description: >-
  Calendly implementation package that allows embedding 
  Calendly booking experience into flutter app with ease.
version: 0.0.1
homepage: https://github.com/eterkit/flutter-packages/tree/main/calendly

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.6
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0

flutter:
  assets:
    - assets/index.html
    - assets/widget.js

import_sorter:
  comments: false