name: edge_detector
description: >-
  Edge detector plugin based on google ml kit object detection.
  Allows basic edge detection for given image.
version: 1.0.0
homepage: https://github.com/eterkit/flutter-packages/tree/main/edge_detector
repository: https://github.com/eterkit/flutter-packages

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0

flutter:
  plugin:
    platforms:
      android:
        package: com.eterkit.edge_detector
        pluginClass: EdgeDetectorPlugin
      ios:
        pluginClass: EdgeDetectorPlugin

import_sorter:
  comments: false
