name: custom_cropper
description: >-
  Dart native image cropper package that allows cropping images 
  with a custom and adjustable shape. 
version: 1.0.3
homepage: https://github.com/eterkit/flutter-packages/tree/main/custom_cropper
repository: https://github.com/eterkit/flutter-packages

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0

flutter:
