name: auto_animated_list
description: >-
  ListView Widget that supports automatic animations 
  when list items are changed.
version: 2.0.0
homepage: https://github.com/eterkit/flutter-packages/tree/main/auto_animated_list
repository: https://github.com/eterkit/flutter-packages
screenshots:
  - description: 'Example of auto animated list.'
    path: example.gif

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  diffutil_dart: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0

flutter:

import_sorter:
  comments: false
