name: example
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0
  responsive_config:
    path: ../

flutter:
  uses-material-design: true

import_sorter:
  comments: false
