name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish if version bumped
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "auto_animated_list"
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: auto_animated_list
          flutter: true
          skipTests: true
      - name: "custom_rating_bar"
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: custom_rating_bar
          flutter: true
          skipTests: true
      - name: "permission_guard"
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: permission_guard
          flutter: true
          skipTests: true